services:
  pgdb:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pg-vector
    environment:
      POSTGRES_USER: danijel
      POSTGRES_PASSWORD: slobomirp7008
      POSTGRES_DB: l2main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"


volumes:
  pgdata: