services:
  pgdb:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pg-vector
    environment:
      POSTGRES_USER: danijel
      POSTGRES_PASSWORD: slobomirp7008
      POSTGRES_DB: l2main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml

    # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Collector metrics
      - "8887:8887"

    # Grafana for visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    volumes:
      - minio-data:/data  # Persistent storage for MinIO data
    environment:
      MINIO_ROOT_USER: minioadmin  # Root user for MinIO
      MINIO_ROOT_PASSWORD: minioadmin  # Root password for MinIO
    command: server /data --console-address ":9001"


volumes:
  pgdata:
  grafana-storage:
  minio-data:
