receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # File log receiver (optional - for reading log files)
  filelog:
    include: [/var/log/*.log]
    operators:
      - type: json_parser
        parse_from: attributes.message

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Add resource attributes
  resource:
    attributes:
      - key: service.name
        value: "my-service"
        action: upsert
      - key: service.version
        value: "1.0.0"
        action: upsert

  # Add attributes for better labeling in Loki
  attributes:
    actions:
      - key: loki.attribute.labels
        value: service.name, service.version, level
        action: insert

exporters:
  # Loki exporter for logs
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [resource, attributes, batch]
      exporters: [loki, debug]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug]

  extensions: []