receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1

  resource:
    attributes:
      - key: service.name
        value: "htec-morpheus"
        action: upsert
      - key: service.version
        value: "1.0.0"
        action: upsert

exporters:
  # Simplified Loki exporter
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    # Remove format and labels - use only basic config

  # OTLP exporter for traces to Jaeger
  otlp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8887"

service:
  telemetry:
    logs:
      level: debug
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki, debug]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/jaeger, debug]

#    metrics:
#      receivers: [otlp]
#      processors: [resource, batch]
#      exporters: [prometheus, debug]